### ISSUE TITLE
Get customers

### ISSUE THREAD

**Issue by wayusei** [wayusei/FonDiDita-m3#11]
Probando directamente desde la api en railway, get customers no me da respuesta, sale el siguiente mensaje.

![image](https://user-images.githubusercontent.com/6761758/201535007-b9bc9b34-51ca-49e9-a011-15fb8266c49f.png)

**Comment by wayusei** [comment]
Revisé y no funcionan los get y el post, por lo que hay que checar todo.

**Comment by albertohgj** [comment]
Se reviso y se realizaron las correciones

**Comment by albertohgj** [comment]
![image](https://user-images.githubusercontent.com/50330386/201545370-2c58a425-9942-4f67-9d5f-351b44c9766c.png)
